Feature/search page
snizhanamohyl/project-y9o2mW7i pull request #12
Opened 2023-07-11 13:36 UTC by uvchuk

2023-07-11 15:03 UTC, snizhanamohyl requested changes

2023-07-11 15:03 UTC, snizhanamohyl commented on src/components/SearchBar/SearchBar.jsx
> +export const SearchBar = () => {
по компонентам домовились за дефолтний експорт, зміни, будь ласка

2023-07-11 15:03 UTC, snizhanamohyl commented on src/components/SearchForm/SearchForm.jsx
> +    setSearchParams({ ...searchConfig, query: query });
query: query -> query

2023-07-11 15:03 UTC, snizhanamohyl commented on src/components/SearchTypeSelector/SearchTypeSelector.jsx
> +        id="searchBy"
навіщо id?

2023-07-11 15:56 UTC, uvchuk commented on src/components/SearchForm/SearchForm.jsx
> +    setSearchParams({ ...searchConfig, query: query });
ок

2023-07-11 15:56 UTC, uvchuk commented on src/components/SearchBar/SearchBar.jsx
> +export const SearchBar = () => {
ок

2023-07-12 10:50 UTC, snizhanamohyl requested changes

2023-07-12 10:50 UTC, snizhanamohyl commented on src/components/SearchBar/SearchBar.jsx
> +    setSearchParams({ type: type ? type : 'query', query: request });
чому type 'query', а не type 'title'?

2023-07-12 10:50 UTC, snizhanamohyl commented on src/components/SearchForm/SearchForm.jsx
> +    navigate(`/search?type=query&query=${e.target[0].value}`);
за такої побудови назви шляху в адресній строці відображається "http://localhost:3000/project-y9o2mW7i/search?type=query&query=salad", а має "http://localhost:3000/project-y9o2mW7i/search/title/salad" думаю

2023-07-12 10:50 UTC, snizhanamohyl commented on src/components/SearchTypeSelector/SearchTypeSelector.jsx
> +        <MenuItem value="query">Title</MenuItem>
все таки мабуть хай буде title замість query, бо query це те, що в інпут введено, а шукаємо ми по тайтлу)

2023-07-12 11:04 UTC, uvchuk commented on src/components/SearchTypeSelector/SearchTypeSelector.jsx
> +        id="searchBy"
так з MUI з документації скопіпастив) Ніби працює і без них, прибираю

2023-07-12 11:04 UTC, uvchuk commented on src/components/SearchBar/SearchBar.jsx
> +    setSearchParams({ type: type ? type : 'query', query: request });
з ТЗ:

2023-07-12 11:08 UTC, uvchuk commented on src/components/SearchForm/SearchForm.jsx
> +    navigate(`/search?type=query&query=${e.target[0].value}`);
Так і повинно бути, searchParams так і працює)

2023-07-12 11:10 UTC, uvchuk commented on src/components/SearchTypeSelector/SearchTypeSelector.jsx
> +        <MenuItem value="query">Title</MenuItem>
Роблю по ТЗ

2023-07-13 17:09 UTC, snizhanamohyl approved these changes

2023-07-13 17:09 UTC, merged