Feature/recipe page
snizhanamohyl/project-y9o2mW7i pull request #17
Opened 2023-07-12 16:46 UTC by NateSSaw

done styles

2023-07-12 21:05 UTC, snizhanamohyl requested changes

2023-07-12 21:05 UTC, snizhanamohyl commented on src/assets/images/checkbox.svg
чому не в спрайт?

2023-07-12 21:05 UTC, snizhanamohyl commented on src/assets/images/mobile/bg-hero-recipe.jpg
з фоном ще розберемося, але треба буде ще оптимізація під ретіну потім

2023-07-12 21:05 UTC, snizhanamohyl commented on src/assets/images/mobile/checkbox.svg
навіщо для різних версій? це ж свг, просто задати іншу ширину та висоту, вона ідеально масштабується)

2023-07-13 09:19 UTC, snizhanamohyl requested changes

2023-07-13 09:19 UTC, snizhanamohyl commented on src/components/RecipePageComponents/Hero/RecipePageHero.styled.js
> +import bgDeskRetina from '../../../assets/images/desktop/recipePage-hero-bg-2x.jpg';
'../../../assets/images/desktop/recipePage-hero-bg-2x.jpg'; можна просто писати 'assets/images/desktop/recipePage-hero-bg-2x.jpg'; (без крапок)

2023-07-13 09:19 UTC, snizhanamohyl commented on src/components/RecipePageComponents/IngredientsItem/Checkbox.js
це в одному файлі компонент та стилі? рознеси

2023-07-13 09:19 UTC, snizhanamohyl commented on src/components/RecipePageComponents/IngredientsItem/RecipePageIngredientsItem.jsx
> +      <ListItem>
якщо RecipePageIngredientsItem компонент, тоді він повертатиме 1 картку таку, треба ще компонент, що буде повертати список цих карток, проходячись по масиву через map, аналогычно як ми вчора робили з RecipesList

2023-07-13 09:19 UTC, snizhanamohyl commented on src/components/RecipePageComponents/IngredientsList/RecipePageIngredientsList.jsx
> +      <IngredientsList>
оцей компонент прийматиме масив, і через map рендерити список карток, винеси його окремо

2023-07-13 09:19 UTC, snizhanamohyl commented on src/pages/RecipePage/RecipePage.jsx
> +  const token =
token тут зайвий походу, логіку з роботи з бекендом в services

2023-07-13 11:35 UTC, snizhanamohyl requested changes

2023-07-13 11:35 UTC, snizhanamohyl commented on src/components/RecipePageComponents/Hero/RecipePageHero.styled.js
> +  @media (min-width: 400px) {
до 450px можна дотягнути

2023-07-13 11:35 UTC, snizhanamohyl commented on src/components/RecipePageComponents/IngredientsList/RecipePageIngredientsList.jsx
> +      <RecipePageIngredientsItem />
тут буде динаміна розмітка, map масиву

2023-07-13 11:35 UTC, snizhanamohyl commented on src/components/RecipePageComponents/IngredientsList/RecipePageIngredientsList.jsx
назви файли всередині папки так само, як називається папка

2023-07-13 14:04 UTC, snizhanamohyl requested changes

2023-07-13 14:04 UTC, snizhanamohyl commented on src/components/RecipePageComponents/IngredientsList/IngredientsList.jsx
> +          key={ingredients.id}
ingredient.id

2023-07-13 14:04 UTC, snizhanamohyl commented on src/components/RecipePageComponents/Instruction/Instruction.jsx
> +  console.log(link);
консоль логи прибери

2023-07-14 23:14 UTC, NateSSaw commented on src/components/RecipePageComponents/IngredientsList/IngredientsList.jsx
> +          key={ingredients.id}
ingredients:  {id: {…},

2023-07-14 23:15 UTC, NateSSaw commented on src/components/RecipePageComponents/IngredientsList/IngredientsList.jsx
> +          key={ingredients.id}
так приходять дані

2023-07-15 00:24 UTC, snizhanamohyl requested changes

2023-07-15 00:24 UTC, snizhanamohyl commented on src/components/RecipePageComponents/Hero/Hero.jsx
> +  const onClick = e => {};
це для чого?

2023-07-15 00:24 UTC, snizhanamohyl commented on src/components/RecipePageComponents/Hero/Hero.styled.js
> +  margin-right: auto;
здається margin-right, margin-left auto не треба якщо justify-content: center;

2023-07-15 00:24 UTC, snizhanamohyl commented on src/components/RecipePageComponents/IngredientsItem/IngredientsItem.jsx
> +          <ImageIngredient alt="photo ingredients" src={id.img} />
в alt id.name

2023-07-15 00:29 UTC, NateSSaw commented on src/components/RecipePageComponents/Hero/Hero.jsx
> +  const onClick = e => {};
там має бути колись додавання до улюблених і зміна надпису на кнопці. я поки видалю

2023-07-15 00:54 UTC, snizhanamohyl approved these changes

2023-07-15 00:55 UTC, merged