add footer
snizhanamohyl/project-y9o2mW7i pull request #18
Opened 2023-07-12 18:18 UTC by VitaliyYakovenko

2023-07-12 20:35 UTC, snizhanamohyl requested changes

2023-07-12 20:35 UTC, snizhanamohyl commented on src/components/BottomBlock/BottomBlock.styled.js
> +    color: #22252A;
юзай var() зі index.css
+за макетом ще opacity: 0.5;

2023-07-12 20:35 UTC, snizhanamohyl commented on src/components/BottomBlock/BottomBlock.styled.js
> +   color: #22252A;
юзай var() зі index.css
+за макетом ще opacity: 0.5;

2023-07-12 20:35 UTC, snizhanamohyl commented on src/components/ButtonsFooter/ButtonsFooter.jsx
> +  const logoHeight = window.innerWidth < 768 ? 12: 16;
юзай хук useWindowWidth

2023-07-12 20:35 UTC, snizhanamohyl commented on src/components/Footer/Footer.jsx
> +
зроби читабельні відступи пліз

2023-07-12 20:35 UTC, snizhanamohyl commented on src/components/Footer/Footer.styled.js
> +export const FooterSection = styled.div`
можеш задати йому footer, не дів, і з компоненту Footer <footer></footer> прибрати

2023-07-12 20:35 UTC, snizhanamohyl commented on src/components/LogoFooter/LogoFooter.jsx
> +    const logoSize = window.innerWidth < 768 ? 32 : 44;
теж хук

2023-07-12 20:35 UTC, snizhanamohyl commented on src/components/NavFooter/NavFooter.jsx
> +      <NavFooterItem>
відформатий код візуально

2023-07-12 20:44 UTC, snizhanamohyl requested changes

2023-07-12 20:44 UTC, snizhanamohyl commented on src/components/ButtonsFooter/ButtonsFooter.styled.js
> +        line-height: 18px;
line-height задаємо відносно (рахуємо line-height/font-size)

2023-07-13 08:01 UTC, VitaliyYakovenko commented on src/components/BottomBlock/BottomBlock.styled.js
> +    color: #22252A;
+

2023-07-13 08:04 UTC, VitaliyYakovenko commented on src/components/BottomBlock/BottomBlock.styled.js
> +   color: #22252A;
+

2023-07-13 08:09 UTC, VitaliyYakovenko commented on src/components/ButtonsFooter/ButtonsFooter.jsx
> +  const logoHeight = window.innerWidth < 768 ? 12: 16;
+

2023-07-13 08:14 UTC, VitaliyYakovenko commented on src/components/Footer/Footer.jsx
> +
+

2023-07-13 08:14 UTC, VitaliyYakovenko commented on src/components/Footer/Footer.styled.js
> +export const FooterSection = styled.div`
+

2023-07-13 08:15 UTC, VitaliyYakovenko commented on src/components/LogoFooter/LogoFooter.jsx
> +    const logoSize = window.innerWidth < 768 ? 32 : 44;
+

2023-07-13 08:16 UTC, VitaliyYakovenko commented on src/components/NavFooter/NavFooter.jsx
> +      <NavFooterItem>
+

2023-07-13 08:19 UTC, VitaliyYakovenko commented on src/components/ButtonsFooter/ButtonsFooter.styled.js
> +        line-height: 18px;
+

2023-07-13 20:58 UTC, snizhanamohyl approved these changes

2023-07-13 20:58 UTC, merged