Feature/user edit modal
snizhanamohyl/project-y9o2mW7i pull request #29
Opened 2023-07-15 12:57 UTC by helenserb

Створила модалку на основі mui 

Мені треба допомога з:
-  позиціонуванням іконок в інпуті (вони зроблені на око через абсолют, я не розумію чому з даними з макета они вcтають інакше;
- з кольором іконок юзера на та карандаша, не виходить іх змінити;
- і взагалі як зроблен інпут type=file. Бо мені поки не зрозуміло як туди фото потім встане...

Дякую.

2023-07-15 14:36 UTC, snizhanamohyl requested changes

2023-07-15 14:36 UTC, snizhanamohyl commented on src/components/Popover/PopoverMenu .jsx
> +  const handleCloseModal = () => {setIsEditModalOpen(false);};
можеш зробити замість 2 функцій одну - const toggleModal= () => {setIsEditModalOpen(status=> !status)};
то просто пропозиція)

2023-07-15 14:36 UTC, snizhanamohyl commented on src/components/EditUserModal/EditUserModal.jsx
> +      <ModalContent>
Modal винеси в окремий компонент EditUserModal
а цей компонент з createPortal буде переюзабельний, щоб можна було б закинути children різні, назви його якось загально

2023-07-15 14:45 UTC, snizhanamohyl commented
- іконкам в спрайті задати stroke, інпут огорнути в дів (у діві іконки та інпут - все один рівень вкладеності). дів по висоті буде як інпут, позиціонуємо іконки відносно діва, при фокусі на інпут додати діву color: (--accent). 
- інпут type=file можеш чекнути на сторінці AddRecipe

2023-07-16 01:59 UTC, helenserb commented on src/components/Popover/PopoverMenu .jsx
> +  const handleCloseModal = () => {setIsEditModalOpen(false);};
зробила

2023-07-16 10:34 UTC, snizhanamohyl requested changes

2023-07-16 10:34 UTC, snizhanamohyl commented on package.json
> +    "react-toastify": "^9.1.3",
toastify не буде, буде нотіфікашка з mui

2023-07-16 10:34 UTC, snizhanamohyl commented on src/assets/sprite.svg
у мене твої зміни в спрайті дивно відображаються, ніби ти його перезаписала
зтягни зміни з мейну та перезапиши тільки свої іконки (або додай нові)

2023-07-16 10:34 UTC, snizhanamohyl commented on src/components/EditUserForm/EditUserForm.jsx
> +        .unwrap()
.unwrap() - не юзала таке) підкажи, для чого використовується тут?

2023-07-16 10:34 UTC, snizhanamohyl commented on src/hooks/useAuth.js
можна просто зробити додатковий селектор в auth/selectors.js

2023-07-16 10:34 UTC, snizhanamohyl commented on src/redux/auth/auth-operations.js
> +      const data = await updateUserInfo(credentials);
функція updateUserInfo буде в цьому файлі, не в services.js
можна її інлайново тут прописати

2023-07-16 10:34 UTC, snizhanamohyl commented on src/services/auth-api.js
цього файлу не буде

2023-07-17 17:27 UTC, snizhanamohyl requested changes

2023-07-17 17:27 UTC, snizhanamohyl commented on package.json
> +    "react-toastify": "^9.1.3",
видали toastify, будь ласка

2023-07-17 17:27 UTC, snizhanamohyl commented on src/components/EditUserForm/EditUserForm.styled.js
> +export const UserIcon = styled.svg``;
порожнє правило, прибери пліз

2023-07-17 17:28 UTC, snizhanamohyl commented
при рефреші юзера скидається аватарка та ім'я, треба пофіксити

2023-07-18 00:24 UTC, snizhanamohyl approved these changes

2023-07-18 00:26 UTC, merged