Welcome page
snizhanamohyl/project-y9o2mW7i pull request #3
Opened 2023-07-09 00:12 UTC by helenserb

2023-07-09 10:24 UTC, snizhanamohyl requested changes

2023-07-09 10:24 UTC, snizhanamohyl commented on src/assets/images/welcomePage/bg.jpg
ти вивантажела картинки разом з градієнтом, а вони мають бути "чисті", градієнт через css додати

2023-07-09 10:24 UTC, snizhanamohyl commented on src/components/AuthNav/AuthNav.jsx
> +      <SignInBtn to="/signIn">SignIn</SignInBtn>
to="/signin" (всі літери з маленької)

2023-07-09 10:24 UTC, snizhanamohyl commented on src/components/AuthNav/AuthNav.styled.jsx
> +  background-color: #8baa36;
усі кольори в css прописуємо через var(), змінні для кольорів можна переглянути у файлі index.css

2023-07-09 10:24 UTC, snizhanamohyl commented on src/components/AuthNav/AuthNav.styled.jsx
> +  line-height: 1.5;
font-size, line-height для цього тексту вже є в загальних стилях, можеш спробувати видалити або заюзати inherit, по ідеї все спрацює)

2023-07-09 10:24 UTC, snizhanamohyl commented on src/components/AuthNav/AuthNav.jsx
> +      <SignInBtn to="/signIn">SignIn</SignInBtn>
Sign In, в тексті пробіл загубила

2023-07-09 10:24 UTC, snizhanamohyl commented on src/components/AuthNav/AuthNav.styled.jsx
> +
додай ще transition: background-color var(--transition-time) var(--transition-function); для плавності зміни стилів при ховері

2023-07-09 10:24 UTC, snizhanamohyl commented on src/components/AuthNav/AuthNav.styled.jsx
> +
transition: border-color var(--transition-time) var(--transition-function), background-color var(--transition-time) var(--transition-function); (чекни ще, як правильно для двох властивостей додавати)

2023-07-09 10:24 UTC, snizhanamohyl commented on src/components/AuthNav/AuthNav.styled.jsx
> +  border: 2px solid #22252a;
можна змінити лише border-color замість перевизначення border

2023-07-09 10:24 UTC, snizhanamohyl commented on src/components/Greeting/Greeting.jsx
> +        src={require('../../assets/svg/logo.svg').default}
прикольно src зробила, для мене нове)

2023-07-09 10:24 UTC, snizhanamohyl commented on src/components/Greeting/Greeting.styled.jsx
> +    (min-resolution: 2dppx) {
можеш посянити, будь ласка, звідки ці значення та що вони означають
"@media (min-device-pixel-ratio: 2),
    (min-resolution: 192dpi),
    (min-resolution: 2dppx)"
я підзабула

2023-07-09 10:24 UTC, snizhanamohyl commented on src/components/Greeting/Greeting.styled.jsx
> +    );
linear-gradient(
      180deg,
      rgba(0, 0, 0, 0.6) 46.3%,
      rgba(0, 0, 0, 0.35) 72.75%,
      rgba(0, 0, 0, 0) 100%
    );
значення градієнту повторюється надалі чимало разів, тому винеси його в змінну файлу index.css і використовуй її

2023-07-09 10:24 UTC, snizhanamohyl commented on src/components/Greeting/Greeting.styled.jsx
> +  @media screen and (min-width: 1200px) {
чому min-width: 1200px? десктоп у нас з 1440px

2023-07-09 10:24 UTC, snizhanamohyl commented on src/components/Greeting/Greeting.styled.jsx
> +      background-image: url('${bgDeskRetina}'),
оцю штуку "(min-device-pixel-ratio: 2),
      (min-resolution: 192dpi),
      (min-resolution: 2dppx)" теж можеш спробувати винести у змінну

2023-07-09 10:24 UTC, snizhanamohyl commented on src/components/Greeting/Greeting.styled.jsx
> +  margin: 0 0 14px 0;
заюзай краще лише нижній марджин, якщо це нічого не зламає

2023-07-09 10:24 UTC, snizhanamohyl commented on src/components/Greeting/Greeting.styled.jsx
> +  letter-spacing: -0.28px;
"  font-size: 14px;
  font-weight: 400;
  line-height: 1.286;
  letter-spacing: -0.28px;" - стандартні значення з index.css, звідси спробуй прибрати

2023-07-09 10:24 UTC, snizhanamohyl commented on src/components/Greeting/Greeting.styled.jsx
> +    letter-spacing: -0.36px;
"  font-size: 18px;
    line-height: 1.3;
    letter-spacing: -0.36px;" - стандартні значення з index.css, звідси спробуй прибрати

2023-07-09 12:41 UTC, helenserb commented on src/components/AuthNav/AuthNav.styled.jsx
> +  background-color: #8baa36;
+ Виправлено на var

2023-07-09 12:49 UTC, helenserb commented on src/components/AuthNav/AuthNav.styled.jsx
> +  line-height: 1.5;
+ Font size видалила - він наслідується
а line-height залишила - бо за макетом він 1.5. А в заг стилях - 1.29

2023-07-09 12:50 UTC, helenserb commented on src/components/AuthNav/AuthNav.jsx
> +      <SignInBtn to="/signIn">SignIn</SignInBtn>
+виправила

2023-07-09 12:53 UTC, helenserb commented on src/components/Greeting/Greeting.styled.jsx
> +  @media screen and (min-width: 1200px) {
+ виправила

2023-07-09 13:00 UTC, helenserb commented on src/components/Greeting/Greeting.styled.jsx
> +  letter-spacing: -0.28px;
+ прибрала, не ламається

2023-07-09 13:03 UTC, helenserb commented on src/components/Greeting/Greeting.styled.jsx
> +    letter-spacing: -0.36px;
Це не можу прибрати. Бо в загальних стилях ці значення з'являються з 1440,  а мені потрібно з 768

2023-07-09 13:08 UTC, helenserb commented on src/components/Greeting/Greeting.styled.jsx
> +  margin: 0 0 14px 0;
+переписала

2023-07-09 13:09 UTC, helenserb commented on src/components/AuthNav/AuthNav.jsx
> +      <SignInBtn to="/signIn">SignIn</SignInBtn>
+виправила

2023-07-09 14:07 UTC, helenserb commented on src/components/Greeting/Greeting.styled.jsx
> +      background-image: url('${bgDeskRetina}'),
+винесла

2023-07-09 14:20 UTC, helenserb commented on src/assets/images/welcomePage/bg.jpg
Я замінила, ле чомусь з макетом не співпадає

2023-07-13 01:03 UTC, snizhanamohyl requested changes

2023-07-13 01:03 UTC, snizhanamohyl commented on src/components/Greeting/Greeting.jsx
> +      {/* <Logo
додай лого

2023-07-13 01:03 UTC, snizhanamohyl commented on src/components/App/App.jsx
> +    <Route path='/signin' element={<RestrictedRoute component={SigninPage} redirectTo='/'/>}></Route>
додай роут поки `<Route path='/welcome' element={<RestrictedRoute component={WelcomePage} redirectTo='/' />}></Route>`

2023-07-13 01:03 UTC, snizhanamohyl commented on src/components/Greeting/Greeting.styled.jsx
> +import bgMobRetina from '../../assets/images/mobile/welcomebg-2x.jpg';
зміни імпорти на 'assets/images/mobile/welcomebg-2x.jpg'; (без крапок спочатку)

2023-07-13 01:03 UTC, snizhanamohyl commented on src/components/Greeting/Greeting.jsx
усі файли стилів називаємо з розширенням js (наприклад, тут Greeting.styled.js)
позмінюй, будь ласка

2023-07-13 01:45 UTC, helenserb commented on src/components/Greeting/Greeting.jsx
> +      {/* <Logo
додала

2023-07-13 01:45 UTC, helenserb commented on src/components/Greeting/Greeting.styled.jsx
> +import bgMobRetina from '../../assets/images/mobile/welcomebg-2x.jpg';
видалила

2023-07-13 01:46 UTC, helenserb commented on src/components/Greeting/Greeting.jsx
змінила

2023-07-13 10:30 UTC, snizhanamohyl approved these changes

2023-07-13 10:37 UTC, merged