404 page
snizhanamohyl/project-y9o2mW7i pull request #4
Opened 2023-07-10 01:22 UTC by helenserb

Створила 404 сторінку, але без фонового зображення.
Хочу запитати чи хтось зробив його вже чи ні. Бо воно перевикористовується на багатьох сторінках

2023-07-12 00:50 UTC, snizhanamohyl requested changes

2023-07-12 00:50 UTC, snizhanamohyl commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +        <Header />
Header в SharedLayout, тут не буде

2023-07-12 00:50 UTC, snizhanamohyl commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +        <Footer/>
Footer в SharedLayout, тут не буде

2023-07-12 00:50 UTC, snizhanamohyl commented on src/components/NotFound/NotFound.styled.js
> +    padding: 100px 0 204px 0;
ніюи достатньо буде padding-bottom: 204px

2023-07-12 00:50 UTC, snizhanamohyl commented on src/components/NotFound/NotFound.styled.js
> +    padding: 138px 0 204px 0;
а тут вже тоді padding-top: 138px

2023-07-12 00:50 UTC, snizhanamohyl commented on src/components/NotFound/NotFound.styled.js
> +  height: 170px;
мабуть ще конкрену ширину варто задати

2023-07-13 02:47 UTC, helenserb commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +        <Header />
done

2023-07-13 02:47 UTC, helenserb commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +        <Footer/>
done

2023-07-13 02:48 UTC, helenserb commented on src/components/NotFound/NotFound.styled.js
> +    padding: 138px 0 204px 0;
done

2023-07-13 02:57 UTC, helenserb commented on src/components/NotFound/NotFound.styled.js
> +  height: 170px;
додала

2023-07-13 10:59 UTC, snizhanamohyl approved these changes

2023-07-13 11:00 UTC, merged